<?php
/** ensure this file is being included by a parent file */
defined( '_JEXEC' ) or die( 'Restricted access' );
?>
<table class="adminlist">
	<tr>
		<td class="tableListHeader" align="left">About jAccounts</td>
	</tr>
	<tr>
    	<td align="center">
        <table width="500" align="center"><tr><td align="center">
        <img src="components/com_jaccounts/images/jaccounts_logo.png" />
        <h1><font color="#FF0000">VERSION 1.5.5</font></h1><h2><strong>Single Site License.</strong></h2>
        	<h2>Details</h2>
            <p>This component is part of a larger system (jForce).  It can be used independently but will function to full capabilities as part of the entire package.  Built to handle all types of quoting and invoicing this portion of jForce is constantly being worked on and expanded.  Please feel free to send your thoughts or ideas to help us improve this product to <a href="mailto: sales@extremejoomla.com">sales@extremejoomla.com</a>.</p>
    
        	<h3>Copyright</h3>
			<p>This is component is a commercial product.  It is NOT a free component.  Please support the community by purchasing components that you use.</p>
        </td></tr></table>
        </td>
   	</tr>
</table>