<?php
$jfConfig['company_name']='Extreme Joomla';
$jfConfig['company_address']='123 Address
Some City, State 12345';
$jfConfig['company_email']='sales@extremejoomla.com';
$jfConfig['terms']='http://www.extremejoomla.com/terms_and_conditions.php';
$jfConfig['access_restrictions']='1';
$jfConfig['currency']='$';
$jfConfig['tax']='17.5';
$jfConfig['auto_invoice']='1';
$jfConfig['invoice_format']='2';
$jfConfig['payment_gateway']='1';
$jfConfig['paypal_address']='sales@extremejoomla.com';
$jfConfig['google_merchant_id']='2342345lkaflk2345235lk23';
$jfConfig['authorize_API']='4836BJag2';
$jfConfig['authorize_API_key']='44GaEA83Q24aN2dD';
$jfConfig['authorize_test']='true';
$jfConfig['2checkout_sid']='56790ujasd82358sdglkj5';
$jfConfig['accepted_quote_subject']='Your quote has been accepted';
$jfConfig['accepted_quote_email']='Dear %CLIENT_NAME%,

Congratulations on accepting the quote!

Your initial invoice should now be available in the client portal.  

Please do not hesitate to contact us with any questions you have.

Sincerely,
%COMPANY_NAME%';
$jfConfig['auto_email']='0';
$jfConfig['new_quote_subject']='Quote: %QUOTE_NAME% is now available';
$jfConfig['new_quote_email']='Dear %CLIENT_NAME%,

The quote entitled %QUOTE_NAME% is now available.

Please do not hesitate to contact us with any questions you have.


Sincerely,
%COMPANY_NAME%';
$jfConfig['new_invoice_subject']='Invoice: %INVOICE_NAME% is now available';
$jfConfig['new_invoice_email']='Dear %CLIENT_NAME%,

The invoice entitled %INVOICE_NAME% is now available.

Please do not hesitate to contact us with any questions you have.

Sincerely,
%COMPANY_NAME%';
$jfConfig['version']='';
?>